In [129]:
import numpy as np
import pandas as pd
import random as ra
import numpy.matlib as nm
import numpy.linalg as na

In [127]:
# Q8
def item_size(arr):
    return({'size':arr.size,'Total Size in Bytes':arr.nbytes})
    # Altenative method --> arr.itemsize*arr.size  (size of 1 element x the total numbers of elemnts)

arr=np.random.randint(4,10,size=(4,9))
print(f"{item_size(arr)}")

{'size': 36, 'Total Size in Bytes': 144}


In [3]:
# Q9

def array_strides(arr):
    return(arr.strides)
    

arr=np.random.randint(4,10,size=(4,9))
print(f"Stride of the Array \n {arr} \n In Bytes --> {array_strides(arr)}")

Stride of the Array 
 [[8 8 4 4 8 5 9 4 8]
 [9 8 4 4 8 6 5 5 8]
 [7 5 7 4 6 6 5 9 4]
 [4 4 6 9 9 9 5 7 6]] 
 In Bytes --> (36, 4)


In [4]:
# Q10
def shape_stride_relationship(arr):
    return({'Shape of Array':arr.shape,'Stride of the Array':arr.strides})


arr=np.random.randint(4,10,size=(4,9))
print(f"{shape_stride_relationship(arr)}")

{'Shape of Array': (4, 9), 'Stride of the Array': (36, 4)}


In [5]:
# Q11

def create_zeros_arrays(n):
    return(np.zeros(n))  # return an Numpy array of n elemnts filled with Zero's

print(f"Zero filled Array \n {create_zeros_arrays(12)}")

Zero filled Array 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
# Q12

def create_ones_matrix(row,col):
    return(np.ones((row,col)))  # returns a matrix filled with 1's

print(f"Ones filled Matrix \n {create_ones_matrix(row=2,col=5)}")

Ones filled Matrix 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
# Q13
def generate_range_array(start,stop,step=1):
    return(np.arange(start,stop,step))

print(f"Ranged Numpy Array  \n {generate_range_array(start=2,stop=10,step=2)}")

Ranged Numpy Array  
 [2 4 6 8]


In [8]:
# Q14
def generate_linear_space(num,start,stop):
    return np.linspace(start,stop,num)  # creating ecenly spaced intervals array

print(f"Line_spaced array : \n {generate_linear_space(10,3,10)}")


Line_spaced array : 
 [ 3.          3.77777778  4.55555556  5.33333333  6.11111111  6.88888889
  7.66666667  8.44444444  9.22222222 10.        ]


In [9]:
#Q15

def create_identity_matrix(n):
    return(np.eye(n,k=0))  # creating identity matrix using eye function
print(f"Identity Matrix : \n {create_identity_matrix(7)}")


Identity Matrix : 
 [[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [10]:
# Q16
import copy

def List_to_Numpyarray(lst):
    return(np.asarray(lst,dtype=np.float32))

my_lst=[45,23,96,45,85,12,20,3.3,45,69]
print(f"List version ---> {my_lst} \n Array Version : \n {List_to_Numpyarray(copy.deepcopy(my_lst))}")

List version ---> [45, 23, 96, 45, 85, 12, 20, 3.3, 45, 69] 
 Array Version : 
 [45.  23.  96.  45.  85.  12.  20.   3.3 45.  69. ]


In [11]:
# Q17

x=np.array([45,23,96,45,85,12,20,3.3,45,69],dtype=np.int16)
new_array=x.view()
print(f"New_Array_Object : {new_array}")

New_Array_Object : [45 23 96 45 85 12 20  3 45 69]


In [12]:
# Q18

def concatinate_axis(arr1,arr2):  #dunction to concatinate two arrays along the Horizontal Axis i.e axis=1
    return(np.hstack((arr1,arr2)))

arr1=np.random.randint(low=4,high=10,size=(3,2))
arr2=np.random.randint(low=4,high=10,size=(3,2))

print(f"Array 1 : \n {arr1} ,\n Array 2 : \n {arr2} , \n  Concatinate Along Horizontal Axis : \n {concatinate_axis(arr1,arr2)}")

Array 1 : 
 [[7 8]
 [9 7]
 [9 9]] ,
 Array 2 : 
 [[7 5]
 [7 5]
 [5 4]] , 
  Concatinate Along Horizontal Axis : 
 [[7 8 7 5]
 [9 7 7 5]
 [9 9 5 4]]


In [13]:
# Q19
arr1=np.random.randint(low=4,high=10,size=(3,2))
arr2=np.random.randint(low=4,high=10,size=(2,3))
print(f"Array 1 : \n{arr1}")
print(f"\nArray 2 : {arr2}")

print(f"\nHorizontally Concatined Array : \n {np.hstack((arr1,arr2.T))}")

Array 1 : 
[[4 8]
 [7 8]
 [5 6]]

Array 2 : [[9 8 5]
 [7 6 5]]

Horizontally Concatined Array : 
 [[4 8 9 7]
 [7 8 8 6]
 [5 6 5 5]]


In [14]:
#Q20
def vertical_Stack_Array(*args):
    return(np.vstack(args))  #stacking of all the lists

print(f"Multiple List's : {([45,20,36,89],[45,78,20,36],[13,79,39])}")
print(f"\nVertical Stacked Array of list : \n {vertical_Stack_Array([45,20,36,89],[45,78,20,36],[13,79,39,42])}")  # sendimng multiple lists as arguments

Multiple List's : ([45, 20, 36, 89], [45, 78, 20, 36], [13, 79, 39])

Vertical Stacked Array of list : 
 [[45 20 36 89]
 [45 78 20 36]
 [13 79 39 42]]


In [15]:
# Q21
def Arrange_NumpyArray(high,low=0,step=1):
    return(np.arange(low,high+1,step,dtype=np.int16))

print(f"Ranged Integer Array : {Arrange_NumpyArray(high=20,low=5,step=4)}")

Ranged Integer Array : [ 5  9 13 17]


In [16]:
# Q22
def EqualspacedValues_NumpyArray():
    return(np.linspace(start=0,stop=1,num=10))

print(f"Ranged Integer Array : {EqualspacedValues_NumpyArray()}")


Ranged Integer Array : [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [17]:
# Q23

def LogspacedValues_NumpyArray():
    return(np.logspace(start=1,stop=1000,num=5))

print(f"Ranged Integer Array : {LogspacedValues_NumpyArray()}")

Ranged Integer Array : [1.00000000e+001 5.62341325e+250             inf             inf
             inf]


C:\Users\abirm\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


In [18]:
# Q24

arr=np.random.randint(low=1,high=101,size=(5,3))
df=pd.DataFrame(arr,columns=["A","B","C"])  #Pandas DataFrame created using Random integers between 1 to 100 using 
df  

A   B   C
0  50  64   6
1   6  52  55
2  69  59  44
3  61  85  20
4  12   8  53

In [19]:
# Q25
df=pd.DataFrame([[45,20,36],[-96,42,-9],[-12,-7,20]],columns=["A","B","C"])
print(f"Original DataFrame : \n {df}")
df["A"]=np.where(df["A"]<0,0,df["A"])  # (condition, True-Action , False Action)
# Alternative approach (wthout numpy)--> df["A"]=df["A"].apply(lambda x : 0 if(x<0) else x)
print(f"\n New DataFrameDataFrame : \n {df}")

Original DataFrame : 
     A   B   C
0  45  20  36
1 -96  42  -9
2 -12  -7  20

 New DataFrameDataFrame : 
     A   B   C
0  45  20  36
1   0  42  -9
2   0  -7  20


In [26]:
#Q26
arr=np.array([10,20,30,40,50])
print(f"Accesing the 5th Element ---> {arr[4]}")

Accesing the 5th Element ---> 50


In [27]:
#Q27
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Fetching elemnt at (1,2) ---> {arr_2d[1,2]}")

Fetching elemnt at (1,2) ---> 6


In [22]:
#Q28
arr=np.array([3,8,2,10,5,7])
print(f"Elements Grater than 5 --> {arr[arr>5]}")

Elements Grater than 5 --> [ 8 10  7]


In [23]:
# 29
arr=np.array([1,2,3,4,5,6,7,8,9])
print(f"Target Slicing --> {arr[2:6]}")  #extracting elements at index position from 2 to 5 inclusive

Target Slicing --> [3 4 5 6]


In [25]:
# Q30
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Traget Extraction of Sub Array --> \n{arr_2d[0:2,1:3]}")

Traget Extraction of Sub Array --> 
[[2 3]
 [5 6]]


# **Loockout Q28,29,25,33,40**

* Good Questions -> 31,33,49,66,49,77,79
* How to insert Elements at specific position on Numpy Array as well delete wise versa
* How to round off the Numpy values both in result as well as in input

In [30]:
#Q31

def extract_index(arr,index):
    output_arr=np.empty(len(index),dtype=np.float16)  #Creating an empty array to store the extracted elements
    for i,ind in enumerate(index):
        if(0<=ind<arr.size):  #condition to check for out-of-bound indexes
            row,col=np.unravel_index(ind,arr.shape)
            output_arr[i]=arr[row,col]
        else:
            output_arr[i]=np.nan # Fill with Null if out of bound index takes place
    return output_arr

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
index = np.array([4, 1, 7])
print(f"Extracted Elements ---> {extract_index(array,index)}")

Extracted Elements ---> [5. 2. 8.]


In [36]:
#Q32
arr=np.array((45,96,20,14,63,78,41,36,91,82,20,1,3,4,7))
threshold=12.5
print(f"Filtered Array --> {arr[arr>threshold]}")

Filtered Array --> [45 96 20 14 63 78 41 36 91 82 20]


In [18]:
#Q33
def ThreeD_Extraction(arr,a1,a2,a3):
    output=np.empty(len(a1))
    counter=0
    for i,j,k in (zip(a1,a2,a3)):
        try:
            output[counter]=arr[i,j,k]
        except ValueError:
            output[counter]=np.nan
        counter+=1
    return output

arr=np.random.randint(low=5,high=16,size=(2,3,3))
a1=np.random.randint(low=0,high=2,size=(5,))
a2=np.random.randint(low=0,high=3,size=(5,))
a3=np.random.randint(low=0,high=3,size=(5,))
print(f"Extracted Elements --> {ThreeD_Extraction(arr,a1,a2,a3)}")

Extracted Elements --> [11. 14.  5. 14.  6.]


In [39]:
#Q34

def Filter_Condition(arr):
    cond1,cond2=arr>(5**2),arr<(4**3)
    return(arr[cond1 & cond2])

arr=np.random.randint(low=14,high=70,size=(11,))
print(f"Array ---> {arr} \n Filtred Array ---> {Filter_Condition(arr)}")

Array ---> [62 57 37 25 36 32 20 48 15 65 50] 
 Filtred Array ---> [62 57 37 36 32 48 50]


In [46]:
#Q35

def Extraction_2D(arr,a1,a2):
    counter=0
    output=np.empty(min(len(a1),len(a2))) # Creating an array to store the extracted arrays
    for i,j in zip(a1,a2):
        try:
            output[counter]=arr[i,j]
        except IndexError:
            output[counter]=np.nan  #Fill with NULL values if IndexError occurs
        counter+=1
    return output

arr=np.random.randint(low=14,high=70,size=(11,3))
a1=np.random.randint(low=0,high=11,size=(ra.randint(10,20),))
a2=np.random.randint(low=0,high=3,size=(ra.randint(10,20),))   
print(f"Original Array : \n {arr},\n Extracted Elements --> {Extraction_2D(arr,a1,a2)}")

Original Array : 
 [[30 68 66]
 [26 54 58]
 [18 23 31]
 [49 65 49]
 [40 42 25]
 [68 62 22]
 [35 68 56]
 [56 34 48]
 [25 19 29]
 [33 57 61]
 [52 61 44]],
 Extracted Elements --> [68. 33. 56. 65. 49. 33. 22. 68. 44. 40. 61.]


In [48]:
#Q36
arr=np.random.randint(low=14,high=70,size=(3,3))
print(f"Original Array : \n {arr} ,\n Scalar addition of 5 : \n {arr+5}")

Original Array : 
 [[32 67 14]
 [67 27 64]
 [23 16 54]] ,
 Scalar addition of 5 : 
 [[37 72 19]
 [72 32 69]
 [28 21 59]]


In [50]:
#Q37
arr1=np.random.randint(low=14,high=70,size=(1,3))
arr2=np.random.randint(low=14,high=70,size=(3,4))

for i in range(3):
    print(arr2[i]*arr1[0,i])

[1560 1500 2040 1920]
[ 416  304  304 1008]
[ 468 1188  288  594]


In [53]:
# Q38
arr1=np.random.randint(low=14,high=70,size=(1,4))
arr2=np.random.randint(low=14,high=70,size=(4,3))

for i in range(4):
    print(arr2[i]+arr1[0,i])


[55 92 88]
[47 36 68]
[ 98 122 124]
[128 125  98]


In [54]:
# Q39
arr1=np.random.randint(low=14,high=70,size=(3,1))
arr2=np.random.randint(low=14,high=70,size=(1,3))

print(f"Addition of Two Array Using Broadcasting {arr1+arr2.T}")

Addition of Two Array Using Broadcasting [[106]
 [ 44]
 [ 86]]


In [4]:
#40
arr1=np.random.randint(low=14,high=70,size=(2,3))
arr2=np.random.randint(low=14,high=70,size=(2,2))

#Trying to broadcasting of Multiplication with Incompatable shapes
try:
    print(arr1*arr2)
except ValueError:
    print("BROADCASTING NOT POSSIBLE DUE TO IN-COMPATABLE SHAPE")

BROADCASTING NOT POSSIBLE DUE TO IN-COMPATABLE SHAPE


In [6]:
#41
arr=np.array([[1,2,3],[4,5,6]])
for i in range(arr.shape[1]):
    print(f"Col{i+1} mean --> {arr[:,i].mean()}")

Col1 mean --> 2.5
Col2 mean --> 3.5
Col3 mean --> 4.5


In [7]:
#Q42
arr=np.array([[1,2,3],[4,5,6]])
for i in range(arr.shape[0]):
    print(f"Max elemnt of Row{i+1} ---> {np.max(arr[i])}")

Max elemnt of Row1 ---> 3
Max elemnt of Row2 ---> 6


In [52]:
#Q43
arr=np.array([[1,2,3],[444,55,6]])
for i in range(arr.shape[1]):
    max=np.max(arr[:,i])
    print(f"Col{i+1} max element Index Position --> {np.where(arr==max)[0]}")

Col1 max element Index Position --> [1]
Col2 max element Index Position --> [1]
Col3 max element Index Position --> [1]


In [17]:
#Q44
def custom_sum(row):
    return(sum(row))

arr=np.array([[1,2,3],[4,5,6]])
for i in range(arr.shape[0]):
    print(f"Sum of all the Row{i+1} elements ---> {custom_sum(arr[i])}")
    

Sum of all the Row1 elements ---> 6
Sum of all the Row2 elements ---> 15


In [16]:
#Q45

arr=np.array([[2,4,6],[36,5,7]])
for i in range(arr.shape[1]):
    if(False in (arr[:,i]%2==0)):
        print(f"Col{i+1} contains a Odd Number")
    else:
        print(f"Col{i+1} contains only Even Numbers")

Col1 contains only Even Numbers
Col2 contains a Odd Number
Col3 contains a Odd Number


In [30]:
#Q46
def Reshape(arr):
    m,n=ra.choice(((1,6),(6,1),(2,3),(3,2)))
    return arr.reshape(m,n)

original_array=np.array([1,2,3,4,5,6])
print(f"Original Array : \n{original_array}\nReshaped Array : \n{Reshape(original_array)}")

Original Array : 
[1 2 3 4 5 6]
Reshaped Array : 
[[1 2 3]
 [4 5 6]]


In [31]:
#Q47
def Flat_Array(mat):
    return(mat.flatten())

input_array=np.array([[1,2,3],[4,5,6]])
print(f"Original Array : \n{input_array}\nReshaped Array : \n{Flat_Array(input_array)}")

Original Array : 
[[1 2 3]
 [4 5 6]]
Reshaped Array : 
[1 2 3 4 5 6]


In [33]:
#Q48
def Concatination(a1,a2):
    return np.concatenate((a1,a2),axis=ra.choice((0,1)))

array1=np.array([[1,2],[3,4]])
array2=np.array([[5,6],[7,8]])
print(f"Original Array1 : \n{array1}\nOriginal Array2 : \n{array2} \nConcatinated Array : \n{Concatination(array1,array2)}")

Original Array1 : 
[[1 2]
 [3 4]]
Original Array2 : 
[[5 6]
 [7 8]] 
Concatinated Array : 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [34]:
#Q49
def Split_Array(arr):
    return(np.split(arr,[1],axis=ra.choice((0,1))))

original_array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Original Array : {original_array}\nSplitted Array's : \n {Split_Array(original_array)}")

Original Array : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Splitted Array's : 
 [array([[1],
       [4],
       [7]]), array([[2, 3],
       [5, 6],
       [8, 9]])]


In [38]:
#Q50
def Operations(arr,ind_i,val_i,ind_del):
    lst=list(arr)
    lst.insert(ind_i[0],val_i[0])
    lst.insert(ind_i[1],val_i[1])
    lst.pop(ind_del[0])
    lst.pop(ind_del[1])
    return(np.asarray(lst))


original_array=np.array([1,2,3,4,5])
indices_to_insert=[2,4]
values_to_insert=[10,11]
indices_to_delete=[1,3]

print(f"Original Array ---> {original_array}\nNew Array ---> {Operations(original_array,indices_to_insert,values_to_insert,indices_to_delete)}")

Original Array ---> [1 2 3 4 5]
New Array ---> [ 1 10  3  4  5]


In [40]:
#Q51
arr1=np.random.randint(low=12,high=30,size=(10,))
arr2=np.array(range(1,11))
print(f"Array 1 --> {arr1}\nArray 2 --> {arr2}\nAddition of Both Array --> {arr1+arr2}")

Array 1 --> [25 18 22 20 26 25 18 12 20 13]
Array 2 --> [ 1  2  3  4  5  6  7  8  9 10]
Addition of Both Array --> [26 20 25 24 31 31 25 20 29 23]


In [42]:
#Q52
arr1=np.array(range(10,0,-1))
arr2=np.array(range(1,11))
print(f"Array 1 --> {arr1}\nArray 2 --> {arr2}\nSubtraction of Both Array --> {arr1-arr2}")

Array 1 --> [10  9  8  7  6  5  4  3  2  1]
Array 2 --> [ 1  2  3  4  5  6  7  8  9 10]
Subtraction of Both Array --> [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [43]:
#Q53
arr1=np.random.randint(low=12,high=30,size=(5,))
arr2=np.array(range(1,6))
print(f"Array 1 --> {arr1}\nArray 2 --> {arr2}\nMultiplication of Both Array --> {arr1*arr2}")

Array 1 --> [13 18 18 20 23]
Array 2 --> [1 2 3 4 5]
Multiplication of Both Array --> [ 13  36  54  80 115]


In [45]:
#Q54
arr1=np.array(range(2,11,2))
arr2=np.array(range(1,6))
print(f"Array 1 --> {arr1}\nArray 2 --> {arr2}\nDivision of Both Array --> {arr1/arr2}")

Array 1 --> [ 2  4  6  8 10]
Array 2 --> [1 2 3 4 5]
Division of Both Array --> [2. 2. 2. 2. 2.]


In [47]:
#Q55
arr1=np.array(range(1,6))
arr2=np.array(range(5,0,-1))
print(f"Array 1 --> {arr1}\nArray 2 --> {arr2}\nExponential of Both Array --> {arr1**arr2}")

Array 1 --> [1 2 3 4 5]
Array 2 --> [5 4 3 2 1]
Exponential of Both Array --> [ 1 16 27 16  5]


In [50]:
#Q56
counter=0
def Substring_Freq(st):
    target="he" #Target substring to look for in the Numpy strings 
    global counter
    while(target in st):
        counter+=1  #counting the number of ocurrance of the substring
        st=st[((st.find(target))+len(target)):]

arr=np.array(["hello","world","hello","numpy","hello"])
for i in arr:
    Substring_Freq(i)

print(f"The Total Frequency of the substring he is ---> {counter}")

The Total Frequency of the substring he is ---> 3


In [11]:
#Q57
lst=""
def Extract_UpperCase(st):
    global lst
    lst=lst+"".join((filter(str.isupper,st)))

arr=np.array(['Hello', 'World', 'OpenAI', 'GPT'])
for i in arr:
    Extract_UpperCase(i)

print(f"Extracted UpperCase Characters from the Array of Strings ---> {arr} is ---> {tuple(lst)}")

Extracted UpperCase Characters from the Array of Strings ---> ['Hello' 'World' 'OpenAI' 'GPT'] is ---> ('H', 'W', 'O', 'A', 'I', 'G', 'P', 'T')


In [11]:
#Q58
def Replacement(st,target_str,sub_str):
    return (st.replace(sub_str,target_str))

arr=np.array(["apple","banana","grape","pineapple"]); sub_str="pple" ; target_str="GPT"
for i in arr:
    print(f"Original String --> {i} || New String --> {Replacement(i,target_str,sub_str)}")

Original String --> apple || New String --> aGPT
Original String --> banana || New String --> banana
Original String --> grape || New String --> grape
Original String --> pineapple || New String --> pineaGPT


In [21]:
#Q59

def Concatinate_String(a1,a2):
    return np.concatenate((a1,a2),axis=0)

arr1,arr2=np.array(["Hello","World"],dtype="<U5"),np.array(["Open","AI"],dtype="<U5")
#arr2.dtype
print(f"Array 1 --> {arr1}\nArray 2 --> {arr2}\n Concatinated Array --> {Concatinate_String(arr1,arr2)}")

Array 1 --> ['Hello' 'World']
Array 2 --> ['Open' 'AI']
 Concatinated Array --> ['Hello' 'World' 'Open' 'AI']


In [141]:
#Q60
def Longest_String_len(arr):
    tu=tuple(map(len,arr))
    print(np.asarray(tu,dtype=int))
    return list(tu)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(f"Array --> {arr}\nLongest String Length = {max(Longest_String_len(arr))}")

[5 6 5 9]


TypeError: 'numpy.int32' object is not callable

In [144]:
#Q61

df=pd.DataFrame(np.random.randint(low=1,high=1001,size=(100,)),columns=["Integers_Data"])
print(f"Mean : {np.mean(df["Integers_Data"])}\nMedian : {np.median(df["Integers_Data"])}\nVariance: {np.var(df["Integers_Data"])}\nStandard Deviation : {np.std(df["Integers_Data"])}")

Mean : 507.6
Median : 523.0
Variance: 99823.79999999999
Standard Deviation : 315.9490465249104


In [42]:
#Q62
df=pd.DataFrame(np.random.randint(low=1,high=101,size=(50,)),columns=["Integers_Data"])
(df.describe()).loc[["25%","75%"]]

Integers_Data
25%           31.0
75%           73.0

In [ ]:
#Q63

In [48]:
#Q64
mat1,mat2=np.matrix(np.random.randint(low=1,high=11,size=(12,)).reshape(3,4)),np.matrix(np.random.randint(low=1,high=11,size=(16,)).reshape(4,4))
print(f"Matrix 1 : \n{mat1}\nMatrix 2 : \n{mat2}\n Dot Product : \n{np.dot(mat1,mat2)}")

Matrix 1 : 
[[8 1 1 6]
 [5 1 1 3]
 [2 6 3 9]]
Matrix 2 : 
[[9 9 7 1]
 [5 5 2 4]
 [7 8 5 2]
 [8 9 5 5]]
 Dot Product : 
[[132 139  93  44]
 [ 81  85  57  26]
 [141 153  86  77]]


In [50]:
#Q65



In [122]:
#Q66
arr_2d=np.array([[1,2,50],[4,54,5],[2,8,2]])

row=np.where(arr_2d.ravel()==5)
print(f"Row and Column coordinate {row}")

Row and Column coordinate (array([5], dtype=int64),)


In [123]:
#Q67
arr=np.random.randint(low=5,high=20,size=(10,))
print(f"Unsorted Array --> {arr}\nSorted Array -->{np.sort(arr)}")

Unsorted Array --> [13 19  9  8 17  8 14 19 19 10]
Sorted Array -->[ 8  8  9 10 13 14 17 19 19 19]


In [60]:
#Q68

arr=np.array([12,25,6,42,8,30])
print(f"Original Array--> {arr}\nFiltred Array >20 {arr[arr>20]}")

Original Array--> [12 25  6 42  8 30]
Filtred Array >20 [25 42 30]


In [65]:
#Q69

arr=np.array([1,5,8,12,15])
print(f"Original Array --> {arr}\nElements Div by 3-->{tuple(filter((lambda x: True if(x%3==0) else False),arr))}")

Original Array --> [ 1  5  8 12 15]
Elements Div by 3-->(12, 15)


In [70]:
#Q70
arr=np.array([10,20,30,40,50])
print(f"Original Array --> {arr}\nElements ≥ 20 and ≤ 40-->{tuple(filter((lambda x: True if(x>=20 and x<=40) else False),arr))}")

Original Array --> [10 20 30 40 50]
Elements ≥ 20 and ≤ 40-->(20, 30, 40)


In [69]:
#Q71
arr=np.array([1,2,3])
print(f"Array-->{arr}\nByte Order-->{arr.dtype}")

Array-->[1 2 3]
Byte Order-->int32


In [71]:
#Q72

arr=np.array([1,2,3],dtype=np.int32)
print(f"Original byte order:{arr.dtype.byteorder}")

arr.byteswap()
print(f"Swapped byte order:{arr.dtype.byteorder}")

Original byte order:=
Swapped byte order:=


In [ ]:
#Q75


In [126]:
#Q76

arr1=np.random.randint(low=1,high=11,size=(10,))
copy_arr=np.copy(arr1)  #Creating a copy of the original array
print(f"Original Array Before Modification in copy --> {arr1}")
copy_arr[5]=7878  #Modification in copy
print(f"Original Array After Modification in copy --> {arr1}")  #No effect on Original Array

Original Array Before Modification in copy --> [3 3 6 9 2 7 5 4 5 2]
Original Array After Modification in copy --> [3 3 6 9 2 7 5 4 5 2]


In [124]:
#Q77

mat=np.asmatrix(np.random.randint(low=5,high=20,size=(3,3)))
print(f"Matrix Before Modifying View_Slice : \n{mat}")
view_slice=mat[0:2,0:2]  #Slicing the original matrix
view_slice[1,1]=9999  #Modifying an elemnt in View Slice
print(f"Matrix After Modifying View_Slice : \n{mat}") #Modification changes are reflected in the Original Matrix too

Matrix Before Modifying View_Slice : 
[[ 6 17 11]
 [10 17 17]
 [15 17 14]]
Matrix After Modifying View_Slice : 
[[   6   17   11]
 [  10 9999   17]
 [  15   17   14]]


In [125]:
#Q78

array_a=np.arange(1,13)
view_b=array_a[0:5]
print(f"Array A before broadcating --> {array_a}")
print(f"Broadcasting Addition of 5 to Array B --> {view_b+5}")
print(f"Array A After broadcating --> {array_a}")  #No changes where reflected

Array A before broadcating --> [ 1  2  3  4  5  6  7  8  9 10 11 12]
Broadcasting Addition of 5 to Array B --> [ 6  7  8  9 10]
Array A After broadcating --> [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [100]:
#Q79

orig_array=np.random.randint(low=1,high=9,size=(2,4))
reshaped_view=np.reshape(orig_array,(4,2))
print(f"Original Array : \n{orig_array}\nReshaped Array : \n{reshaped_view}") 
reshaped_view[3,1]=-999  #Changing an elemnt in Reshaped_view array
print("\nAFTER MODIFICATION \n")
print(f"Original Array : \n{orig_array}\nReshaped Array : \n{reshaped_view}") #Modification changes are reflected in the Original Array too

Original Array : 
[[7 1 1 5]
 [5 8 1 2]]
Reshaped Array : 
[[7 1]
 [1 5]
 [5 8]
 [1 2]]

AFTER MODIFICATION 

Original Array : 
[[   7    1    1    5]
 [   5    8    1 -999]]
Reshaped Array : 
[[   7    1]
 [   1    5]
 [   5    8]
 [   1 -999]]


In [101]:
#Q80
data=np.random.randint(low=1,high=20,size=(3,4))   #Creating an Array of Random integers of size 3x4
copy_data=data[data>5] #Creating a copy of the Filtred Array
print(data)
print("\n",copy_data)
copy_data[5]=777777  #Modifying an element in the copy_data array
print("\nAFTER MODIFICATION \n")
print("\n",data)  #No effect on the Original data Array

[[15 17  4 17]
 [14 18 13 18]
 [ 9 17  3  8]]

 [15 17 17 14 18 13 18  9 17  8]

AFTER MODIFICATION 


 [[15 17  4 17]
 [14 18 13 18]
 [ 9 17  3  8]]


In [85]:
#Q81
A,B=np.asmatrix(np.random.randint(low=5,high=20,size=(3,2))),np.asmatrix(np.random.randint(low=5,high=20,size=(3,2)))
print(f"Matrix 1: \n{A}\nMatrix 2 : \n{B}\nMatrix 1 + Matrix 2 : \n {A+B}\nMatrix 1 - Matrix 2 : \n {A-B}")

Matrix 1: 
[[18  8]
 [15 14]
 [13 19]]
Matrix 2 : 
[[11 18]
 [ 9 13]
 [10 17]]
Matrix 1 + Matrix 2 : 
 [[29 26]
 [24 27]
 [23 36]]
Matrix 1 - Matrix 2 : 
 [[  7 -10]
 [  6   1]
 [  3   2]]


In [83]:
#Q82
C,D=np.asmatrix(np.random.randint(low=5,high=20,size=(3,2))),np.asmatrix(np.random.randint(low=5,high=20,size=(2,4)))
print(f"Matrix 1: \n{C}\nMatrix 2 : \n{D}\n Matrix 1 X Matrix 2 : \n {C@D}")

Matrix 1: 
[[ 9  5]
 [ 5 16]
 [18 12]]
Matrix 2 : 
[[10  8 13  8]
 [11 18 18 13]]
 Matrix 1 X Matrix 2 : 
 [[145 162 207 137]
 [226 328 353 248]
 [312 360 450 300]]


In [81]:
#Q83
E=np.asmatrix(np.random.randint(low=5,high=20,size=(4,3)))
print(f"Matrix : \n{E}\n Transpose_of_Matrix : \n{E.T}")

Matrix : 
[[18 15 18]
 [14  7 10]
 [14 11  8]
 [14 15 18]]
 Transpose_of_Matrix : 
[[18 14 14 14]
 [15  7 11 15]
 [18 10  8 18]]


In [80]:
#Q84
F=np.asmatrix(np.random.randint(low=5,high=20,size=(3,3)))
print(f"Matrix : \n{F}\n Determinant_of_Matrix : \n{na.det(F)}")

Matrix : 
[[16  8 17]
 [ 5 15 14]
 [18 17  9]]
 Determinant_of_Matrix : 
-3137.0000000000014


In [79]:
#Q85
G=np.matrix(np.random.randint(low=5,high=12,size=(3,3)))
print(f"Matrix : \n{G}\n Inverse_of_Matrix : \n{na.inv(G)}")

Matrix : 
[[ 9  7 10]
 [11  8  7]
 [ 7 11  5]]
 Inverse_of_Matrix : 
[[-0.13454545  0.27272727 -0.11272727]
 [-0.02181818 -0.09090909  0.17090909]
 [ 0.23636364 -0.18181818 -0.01818182]]
